services:
  mysql:
    image: 'mysql:8.4.7'
    container_name: biblioteca_personal
    environment:
      MYSQL_DATABASE: biblioteca_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - biblioteca_personal:/var/lib/mysql

volumes:
  biblioteca_personal: